In [1]:
import pandas as pd
import numpy as np

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.impute import KNNImputer
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression

In [6]:
df=pd.read_csv("knn_imputer.csv",usecols=["Age","Pclass","Fare","Survived"])

In [8]:
df.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [9]:
df.isnull().mean()

Survived    0.000000
Pclass      0.000000
Age         0.198653
Fare        0.000000
dtype: float64

In [10]:
#USING KNN IMPUTER

In [11]:
x=df.drop(columns=["Survived"])
y=df["Survived"]

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [15]:
x_train.head()

     Pclass   Age     Fare
331       1  45.5  28.5000
733       2  23.0  13.0000
382       3  32.0   7.9250
704       3  26.0   7.8542
813       3   6.0  31.2750

In [ ]:
#KNN Imputer
knn=KNNImputer() #--> by default n_neighbors=5 and weights=uniform

x_train_knn=knn.fit_transform(x_train)
x_test_knn=knn.transform(x_test)

In [18]:
x_train_knn_df=pd.DataFrame(x_train_knn,columns=x_train.columns)

In [20]:
x_train_knn_df.head()

   Pclass   Age     Fare
0     1.0  45.5  28.5000
1     2.0  23.0  13.0000
2     3.0  32.0   7.9250
3     3.0  26.0   7.8542
4     3.0   6.0  31.2750

In [22]:
x_train_knn_df.isnull().mean()

Pclass    0.0
Age       0.0
Fare      0.0
dtype: float64

In [25]:
lr=LogisticRegression()    #--> because output column is classification 

lr.fit(x_train_knn,y_train)

y_pred_knn=lr.predict(x_test_knn)

print("LR with KNN Imputer:",accuracy_score(y_test,y_pred_knn))

LR with KNN Imputer: 0.7430167597765364

In [ ]:
#Using Simple Imputer --> by-default is mean only.

si=SimpleImputer()

x_train_si=si.fit_transform(x_train)
x_test_si=si.transform(x_test)

In [29]:
lr2=LogisticRegression()

lr2.fit(x_train_si,y_train)
y_pred_si=lr2.predict(x_test_si)
print("LR with Simple Imputer:",accuracy_score(y_test,y_pred_si))

LR with Simple Imputer: 0.7374301675977654

In [31]:
#you can modify knn imputer by changing n_neighbors,weights

In [33]:
knn2=KNNImputer(n_neighbors=2)

x_train_knn2=knn2.fit_transform(x_train)
x_test_knn2=knn2.transform(x_test)

In [34]:
lr_knn2=LogisticRegression()
lr_knn2.fit(x_train_knn2,y_train)
y_pred_knn2=lr_knn2.predict(x_test_knn2)
print("LR with KNN Imputer (n_neighbors=2):",accuracy_score(y_test,y_pred_knn2))

LR with KNN Imputer (n_neighbors=2): 0.7430167597765364

In [35]:
knn2=KNNImputer(n_neighbors=3)

x_train_knn2=knn2.fit_transform(x_train)
x_test_knn2=knn2.transform(x_test)

In [36]:
lr_knn2=LogisticRegression()
lr_knn2.fit(x_train_knn2,y_train)
y_pred_knn2=lr_knn2.predict(x_test_knn2)
print("LR with KNN Imputer (n_neighbors=3):",accuracy_score(y_test,y_pred_knn2))

LR with KNN Imputer (n_neighbors=3): 0.7430167597765364

In [ ]:
knn2=KNNImputer(n_neighbors=10)

x_train_knn2=knn2.fit_transform(x_train)
x_test_knn2=knn2.transform(x_test)

In [39]:
lr_knn2=LogisticRegression()
lr_knn2.fit(x_train_knn2,y_train)
y_pred_knn2=lr_knn2.predict(x_test_knn2)
print("LR with KNN Imputer (n_neighbors=10):",accuracy_score(y_test,y_pred_knn2))

LR with KNN Imputer (n_neighbors=10): 0.7430167597765364

In [50]:
knn2=KNNImputer(n_neighbors=5,weights="distance")

x_train_knn2=knn2.fit_transform(x_train)
x_test_knn2=knn2.transform(x_test)

In [52]:
lr_knn2=LogisticRegression()
lr_knn2.fit(x_train_knn2,y_train)
y_pred_knn2=lr_knn2.predict(x_test_knn2)
print("LR with KNN Imputer (n_neighbors=5,weights='distance'):",accuracy_score(y_test,y_pred_knn2))

LR with KNN Imputer (n_neighbors=5,weights='distance'): 0.7374301675977654