In [1]:
import pandas as pd

In [3]:
df=pd.DataFrame({
    "Room":['A15',"G56","B22","C9"]
})

In [5]:
df.to_csv("Room.csv",index=False)

In [7]:
df

  Room
0  A15
1  G56
2  B22
3   C9

In [ ]:
#Extracting alphabet part

df["Room_Letter"]=df["Room"].str.extract('([A-Za-z]+)')

#([A-Za-z]+) means: take alphabet only

In [13]:
df

  Room Room_Letter
0  A15           A
1  G56           G
2  B22           B
3   C9           C

In [ ]:
#Extracting numerical part

df["Room_Number"]=df["Room"].str.extract('(\d+)') # \d python read escape chr.that why used \\d

<>:3: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:3: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\maner\AppData\Local\Temp\ipykernel_14704\947466558.py:3: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  df["Room_Number"]=df["Room"].str.extract('(\d+)')

In [29]:
df["Room_Number"]=df["Room"].str.extract('(\\d+)') # \\d

In [16]:
df

  Room Room_Letter Room_Number
0  A15           A          15
1  G56           G          56
2  B22           B          22
3   C9           C           9

In [19]:
df.info()
#here the Room_number column is string need to br int.

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Room         4 non-null      str
 1   Room_Letter  4 non-null      str
 2   Room_Number  4 non-null      str
dtypes: str(3)
memory usage: 228.0 bytes

In [24]:
df["Room_Number"]=df["Room_Number"].astype("int32")

In [25]:
df

  Room Room_Letter  Room_Number
0  A15           A           15
1  G56           G           56
2  B22           B           22
3   C9           C            9

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Room         4 non-null      str
 1   Room_Letter  4 non-null      str
 2   Room_Number  4 non-null      str
dtypes: str(3)
memory usage: 228.0 bytes

In [32]:
df=pd.DataFrame({
    "Mixed":["1","2","a","u","o","8"]
})

In [34]:
df.to_csv("mixed.csv")

In [36]:
df

  Mixed
0     1
1     2
2     a
3     u
4     o
5     8

In [38]:
df["mixed_letter"]=df["Mixed"].str.extract('([A-Za-z]+)')

In [39]:
df

  Mixed mixed_letter
0     1          NaN
1     2          NaN
2     a            a
3     u            u
4     o            o
5     8          NaN

In [41]:
df["mixed_number"]=df["Mixed"].str.extract('(\\d+)')

In [43]:
df

  Mixed mixed_letter mixed_number
0     1          NaN            1
1     2          NaN            2
2     a            a          NaN
3     u            u          NaN
4     o            o          NaN
5     8          NaN            8

In [48]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Mixed         6 non-null      str
 1   mixed_letter  3 non-null      str
 2   mixed_number  3 non-null      str
dtypes: str(3)
memory usage: 276.0 bytes

In [51]:
df["mixed_number"]=df["mixed_number"].fillna(0)

In [53]:
df

  Mixed mixed_letter mixed_number
0     1          NaN            1
1     2          NaN            2
2     a            a            0
3     u            u            0
4     o            o            0
5     8          NaN            8

In [55]:
df["mixed_letter"]=df["mixed_letter"].fillna("No_char")

In [57]:
df

  Mixed mixed_letter mixed_number
0     1      No_char            1
1     2      No_char            2
2     a            a            0
3     u            u            0
4     o            o            0
5     8      No_char            8

In [59]:
df["mixed_number"]=df["mixed_number"].astype("int32")

In [60]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Mixed         6 non-null      str
 1   mixed_letter  6 non-null      str
 2   mixed_number  6 non-null      int32
dtypes: int32(1), str(2)
memory usage: 252.0 bytes