In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [34]:
titanic=pd.read_csv("titanic.csv")

In [35]:
titanic.head(2)

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C

[2 rows x 12 columns]

In [36]:
titanic.shape

(891, 12)

In [37]:
titanic.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [38]:
titanic=titanic[["Survived","Pclass","Sex","Age","SibSp","Parch","Fare","Embarked"]]

In [39]:
titanic.head(2)

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C

In [40]:
titanic.shape

(891, 8)

In [41]:
x=titanic.drop(columns=["Survived"])
y=titanic[["Survived"]]

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [42]:
x_train.sample(5)

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
711       1    male   NaN      0      0  26.5500        S
218       1  female  32.0      0      0  76.2917        C
197       3    male  42.0      0      1   8.4042        S
770       3    male  24.0      0      0   9.5000        S
444       3    male   NaN      0      0   8.1125        S

In [43]:
x_test.sample(5)

     Pclass     Sex   Age  SibSp  Parch      Fare Embarked
412       1  female  33.0      1      0   90.0000        Q
505       1    male  18.0      1      0  108.9000        C
55        1    male   NaN      0      0   35.5000        S
27        1    male  19.0      3      2  263.0000        S
97        1    male  23.0      0      1   63.3583        C

In [44]:
x_train.isnull().sum()

Pclass        0
Sex           0
Age         141
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [45]:
x_test.isnull().sum()

Pclass       0
Sex          0
Age         36
SibSp        0
Parch        0
Fare         0
Embarked     0
dtype: int64

In [46]:
x_train.head(3)

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
140       3  female   NaN      0      2  15.2458        C
439       2    male  31.0      0      0  10.5000        S
817       2    male  31.0      1      1  37.0042        C

SINGLE COLUMN TRANSFORMER-->USING COLUMN INDEX NUMBER

In [47]:
trf=ColumnTransformer([("imputer_age",SimpleImputer(),[2]),
                       ("imputer_embarked",SimpleImputer(strategy="most_frequent"),[6]),
                       ("ohe_sex_embarked",OneHotEncoder(sparse_output=False,handle_unknown="ignore"),[1,6])],remainder="passthrough")

In [49]:
pipe=Pipeline([("trf",trf)])

In [58]:
trf.get_feature_names_out()

array(['imputer_age__Age', 'imputer_embarked__Embarked',
       'ohe_sex_embarked__Sex_female', 'ohe_sex_embarked__Sex_male',
       'ohe_sex_embarked__Embarked_C', 'ohe_sex_embarked__Embarked_Q',
       'ohe_sex_embarked__Embarked_S', 'ohe_sex_embarked__Embarked_nan',
       'remainder__Pclass', 'remainder__SibSp', 'remainder__Parch',
       'remainder__Fare'], dtype=object)

In [52]:
pipe_df=pipe.fit_transform(x_train)

In [54]:
pipe_df

array([[29.745183887915935, 'C', 1.0, ..., 0.0, 2.0, 15.2458],
       [31.0, 'S', 0.0, ..., 0.0, 0.0, 10.5],
       [31.0, 'C', 0.0, ..., 1.0, 1.0, 37.0042],
       ...,
       [29.745183887915935, 'Q', 0.0, ..., 0.0, 0.0, 7.7333],
       [36.0, 'S', 1.0, ..., 1.0, 0.0, 17.4],
       [60.0, 'S', 0.0, ..., 1.0, 1.0, 39.0]],
      shape=(712, 12), dtype=object)

In [56]:
x_train.head(1)

     Pclass     Sex  Age  SibSp  Parch     Fare Embarked
140       3  female  NaN      0      2  15.2458        C

In [55]:
pd.DataFrame(pipe_df)

            0  1    2    3    4    5    6    7    8    9    10       11
0    29.745184  C  1.0  0.0  1.0  0.0  0.0  0.0  3.0  0.0  2.0  15.2458
1         31.0  S  0.0  1.0  0.0  0.0  1.0  0.0  2.0  0.0  0.0     10.5
2         31.0  C  0.0  1.0  1.0  0.0  0.0  0.0  2.0  1.0  1.0  37.0042
3         20.0  C  0.0  1.0  1.0  0.0  0.0  0.0  3.0  0.0  0.0   4.0125
4         21.0  S  0.0  1.0  0.0  0.0  1.0  0.0  3.0  0.0  0.0     7.25
..         ... ..  ...  ...  ...  ...  ...  ...  ...  ...  ...      ...
707       39.0  C  1.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0  83.1583
708       19.0  S  1.0  0.0  0.0  0.0  1.0  0.0  3.0  1.0  0.0   7.8542
709  29.745184  Q  0.0  1.0  0.0  1.0  0.0  0.0  3.0  0.0  0.0   7.7333
710       36.0  S  1.0  0.0  0.0  0.0  1.0  0.0  3.0  1.0  0.0     17.4
711       60.0  S  0.0  1.0  0.0  0.0  1.0  0.0  2.0  1.0  1.0     39.0

[712 rows x 12 columns]

In [ ]:
#extra column is 7 index column ohe_sex_embarked__Embarked_nan ,because ,ohe use original embarked,
#not imputer_embarked.so used original embarked ohe separate create nan column..
#that why i get in that column 0.0..

#and also the problem is while using single column transformation-> all transformation run same time ,so if u want to used imputer_embarked,not possible because of all transformer run same time so ohe,used original Encoder.and finally its create embarked column for imputer ,and 0he for embarked_c,embarked_s,embarked_q,and embarked_nan.But its not the write way.
If you want to used imputer Embarked then you have to used separate pipeline.for embarked
like this below is the solution.

In [62]:
x_train.head(2)

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
140       3  female   NaN      0      2  15.2458        C
439       2    male  31.0      0      0  10.5000        S

In [61]:
embarked_pipe=Pipeline([("imputer_embarked",SimpleImputer(strategy="most_frequent")),
                        ("ohe_embarked",OneHotEncoder(sparse_output=False,handle_unknown="ignore"))])

In [64]:
trf=ColumnTransformer([("imputer_age",SimpleImputer(),[2]),
                       ("ohe_sex",OneHotEncoder(sparse_output=False,handle_unknown="ignore"),[1]),
                       ("embarked_imp_ohe",embarked_pipe,[6])],remainder="passthrough")

In [71]:
trf.get_feature_names_out()

array(['imputer_age__Age', 'ohe_sex__Sex_female', 'ohe_sex__Sex_male',
       'embarked_imp_ohe__Embarked_C', 'embarked_imp_ohe__Embarked_Q',
       'embarked_imp_ohe__Embarked_S', 'remainder__Pclass',
       'remainder__SibSp', 'remainder__Parch', 'remainder__Fare'],
      dtype=object)

In [69]:

pipe=Pipeline([("trf",trf)])

In [73]:
df=pipe.fit_transform(x_train)

In [74]:
df

array([[29.74518389,  1.        ,  0.        , ...,  0.        ,
         2.        , 15.2458    ],
       [31.        ,  0.        ,  1.        , ...,  0.        ,
         0.        , 10.5       ],
       [31.        ,  0.        ,  1.        , ...,  1.        ,
         1.        , 37.0042    ],
       ...,
       [29.74518389,  0.        ,  1.        , ...,  0.        ,
         0.        ,  7.7333    ],
       [36.        ,  1.        ,  0.        , ...,  1.        ,
         0.        , 17.4       ],
       [60.        ,  0.        ,  1.        , ...,  1.        ,
         1.        , 39.        ]], shape=(712, 10))

In [75]:
pd.DataFrame(df)

             0    1    2    3    4    5    6    7    8        9
0    29.745184  1.0  0.0  1.0  0.0  0.0  3.0  0.0  2.0  15.2458
1    31.000000  0.0  1.0  0.0  0.0  1.0  2.0  0.0  0.0  10.5000
2    31.000000  0.0  1.0  1.0  0.0  0.0  2.0  1.0  1.0  37.0042
3    20.000000  0.0  1.0  1.0  0.0  0.0  3.0  0.0  0.0   4.0125
4    21.000000  0.0  1.0  0.0  0.0  1.0  3.0  0.0  0.0   7.2500
..         ...  ...  ...  ...  ...  ...  ...  ...  ...      ...
707  39.000000  1.0  0.0  1.0  0.0  0.0  1.0  1.0  1.0  83.1583
708  19.000000  1.0  0.0  0.0  0.0  1.0  3.0  1.0  0.0   7.8542
709  29.745184  0.0  1.0  0.0  1.0  0.0  3.0  0.0  0.0   7.7333
710  36.000000  1.0  0.0  0.0  0.0  1.0  3.0  1.0  0.0  17.4000
711  60.000000  0.0  1.0  0.0  0.0  1.0  2.0  1.0  1.0  39.0000

[712 rows x 10 columns]

SINGLE COLUMN TRANSFORMER-->COLUMN NAME

In [77]:
x_train.head(1)

     Pclass     Sex  Age  SibSp  Parch     Fare Embarked
140       3  female  NaN      0      2  15.2458        C

In [79]:
trf=ColumnTransformer([("impute_age",SimpleImputer(),["Age"]),
                       ("imputer_embarked",SimpleImputer(strategy="most_frequent"),["Embarked"]),
                       ("ohe_sex_embarked",OneHotEncoder(sparse_output=False,handle_unknown="ignore"),["Sex","Embarked"])],remainder="passthrough")

In [81]:
pipe=Pipeline([("trf",trf)])

In [ ]:
pipe.fit_transform(x_train)

#same as above u done for index column number

array([[29.745183887915935, 'C', 1.0, ..., 0.0, 2.0, 15.2458],
       [31.0, 'S', 0.0, ..., 0.0, 0.0, 10.5],
       [31.0, 'C', 0.0, ..., 1.0, 1.0, 37.0042],
       ...,
       [29.745183887915935, 'Q', 0.0, ..., 0.0, 0.0, 7.7333],
       [36.0, 'S', 1.0, ..., 1.0, 0.0, 17.4],
       [60.0, 'S', 0.0, ..., 1.0, 1.0, 39.0]],
      shape=(712, 12), dtype=object)

#here its create embarked of imputer and embarked of ohe,em_c,em_s,em_q,but we want imputer embarked work on ohe.but ohe use original embarked from dataset..for that

In [85]:
x_train.head(2)

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
140       3  female   NaN      0      2  15.2458        C
439       2    male  31.0      0      0  10.5000        S

In [84]:
embarked_pipe=Pipeline([("imputer_embarked",SimpleImputer(strategy="most_frequent")),
                        ("ohe_embarked",OneHotEncoder(sparse_output=False,handle_unknown="ignore"))])

In [87]:
trf=ColumnTransformer([("imputer_age",SimpleImputer(),["Age"]),
                       ("ohe_sex",OneHotEncoder(sparse_output=False,handle_unknown="ignore"),["Sex"]),
                       ("embarked_imp_ohe",embarked_pipe,["Embarked"])],remainder="passthrough")

In [89]:
pipe=Pipeline([("trf",trf)])

In [90]:
pipe.fit_transform(x_train)

array([[29.74518389,  1.        ,  0.        , ...,  0.        ,
         2.        , 15.2458    ],
       [31.        ,  0.        ,  1.        , ...,  0.        ,
         0.        , 10.5       ],
       [31.        ,  0.        ,  1.        , ...,  1.        ,
         1.        , 37.0042    ],
       ...,
       [29.74518389,  0.        ,  1.        , ...,  0.        ,
         0.        ,  7.7333    ],
       [36.        ,  1.        ,  0.        , ...,  1.        ,
         0.        , 17.4       ],
       [60.        ,  0.        ,  1.        , ...,  1.        ,
         1.        , 39.        ]], shape=(712, 10))