In [2]:
import pandas as pd
import numpy as np

In [139]:
titanic=pd.read_csv("titanic.csv")

In [140]:
titanic.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [141]:
titanic=titanic[["Survived","Pclass","Sex","Age","SibSp","Parch","Fare","Embarked"]]

In [142]:
titanic.head(3)

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S

In [14]:
titanic["Sex"].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [16]:
titanic["Embarked"].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [18]:
titanic.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [26]:
titanic.duplicated()
titanic.iloc[883:888,:]

     Survived  Pclass     Sex   Age  SibSp  Parch    Fare Embarked
883         0       2    male  28.0      0      0  10.500        S
884         0       3    male  25.0      0      0   7.050        S
885         0       3  female  39.0      0      5  29.125        Q
886         0       2    male  27.0      0      0  13.000        S
887         1       1  female  19.0      0      0  30.000        S

In [24]:
titanic.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
886     True
887    False
888    False
889    False
890    False
Length: 891, dtype: bool

In [27]:
titanic.head(3)

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S

In [143]:
from sklearn.model_selection import train_test_split

x=titanic[["Pclass","Sex","Age","SibSp","Parch","Fare","Embarked"]]
y=titanic[["Survived"]]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [84]:
x_train.head(2)

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
140       3  female   NaN      0      2  15.2458        C
439       2    male  31.0      0      0  10.5000        S

In [85]:
y_train.head(2)

     Survived
140         0
439         0

In [86]:
x_test.head(2)

     Pclass   Sex  Age  SibSp  Parch     Fare Embarked
495       3  male  NaN      0      0  14.4583        C
648       3  male  NaN      0      0   7.5500        S

In [87]:
y_test.head(2)

     Survived
495         0
648         0

In [46]:
x_train.shape,x_test.shape

((712, 7), (179, 7))

In [48]:
y_train.shape,y_test.shape

((712, 1), (179, 1))

In [123]:
x_train.head(2)

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
140       3  female   NaN      0      2  15.2458        C
439       2    male  31.0      0      0  10.5000        S

In [49]:
#Column Transformer

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
#simpleImputer
trf1=ColumnTransformer([
    ("imputer_age",SimpleImputer(),[2]),   #by-default apply mean to age column
    ("imputer-embarked",SimpleImputer(strategy="most_frequent"),[6])
],remainder="passthrough")

In [125]:
trf1

ColumnTransformer(remainder='passthrough',
                  transformers=[('imputer_age', SimpleImputer(), [2]),
                                ('imputer-embarked',
                                 SimpleImputer(strategy='most_frequent'),
                                 [6])])

In [58]:
#one-hot-encoder

In [154]:
from sklearn.preprocessing import OneHotEncoder

trf2=ColumnTransformer([
    ("ohe_sex_embarked",OneHotEncoder(sparse_output=False,handle_unknown="ignore"),[1,6])
])

In [155]:
from sklearn.preprocessing import MinMaxScaler

trf3=ColumnTransformer([
    ("scaler",MinMaxScaler(),slice(0,10))
])

In [156]:
#pipeline

from sklearn.pipeline import Pipeline

pipe=Pipeline([
    ("trf1",trf1),
    ("trf2",trf2),
    ("trf3",trf3)
    
])

In [136]:
pipe

Pipeline(steps=[('trf1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('imputer_age',
                                                  SimpleImputer(), [2]),
                                                 ('imputer-embarked',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [6])])),
                ('trf2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe_sex_embarked',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1, 6])])),
                ('trf3',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('scaler', MinMaxScaler(),
                                                  slice(0, 10, None))]))])

In [157]:
x_train_transformed=pipe.fit_transform(x_train)

In [158]:
x_train_transformed

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]], shape=(712, 10))

In [ ]:
# trf=ColumnTransformer([
#     ("imputer_age",SimpleImputer(),["Age"]),
#     ("imputer_embarked",SimpleImputer(strategy="most_frequent"),["Embarked"]),
#     ("ohe_sex_embarked",OneHotEncoder(sparse_output=False,handle_unknown="ignore"),["Sex","Embarked"]),
# ],remainder="passthrough")

In [ ]:
# pipe=Pipeline([
#     ("preprocessing",trf)
# ])

In [ ]:
# x_train_final = pipe.fit_transform(x_train)
# x_test_final = pipe.transform(x_test)

In [159]:
# x_train_final

In [160]:
# pd.DataFrame(x_train_final,columns=trf.get_feature_names_out())

In [231]:
x_train.head(2)

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
140       3  female   NaN      0      2  15.2458        C
439       2    male  31.0      0      0  10.5000        S

In [239]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

trf1 = ColumnTransformer([

    ("age_imputer",
     SimpleImputer(),
     [2]),

    ("embarked_imputer",
     SimpleImputer(strategy="most_frequent"),
     [6])

], remainder="passthrough")

In [240]:
x_train_trf1=trf1.fit_transform(x_train)

In [241]:
x_train_trf1

array([[29.745183887915935, 'C', 3, ..., 0, 2, 15.2458],
       [31.0, 'S', 2, ..., 0, 0, 10.5],
       [31.0, 'C', 2, ..., 1, 1, 37.0042],
       ...,
       [29.745183887915935, 'Q', 3, ..., 0, 0, 7.7333],
       [36.0, 'S', 3, ..., 1, 0, 17.4],
       [60.0, 'S', 2, ..., 1, 1, 39.0]], shape=(712, 7), dtype=object)

In [242]:
x_train_trf1=pd.DataFrame(x_train_trf1,columns=["Age","Embarked","Pclass","Sex","SibSp","Parch","Fare"],index=x_train.index)

In [243]:
x_train_trf1

           Age Embarked Pclass     Sex SibSp Parch     Fare
140  29.745184        C      3  female     0     2  15.2458
439       31.0        S      2    male     0     0     10.5
817       31.0        C      2    male     1     1  37.0042
378       20.0        C      3    male     0     0   4.0125
491       21.0        S      3    male     0     0     7.25
..         ...      ...    ...     ...   ...   ...      ...
835       39.0        C      1  female     1     1  83.1583
192       19.0        S      3  female     1     0   7.8542
629  29.745184        Q      3    male     0     0   7.7333
559       36.0        S      3  female     1     0     17.4
684       60.0        S      2    male     1     1     39.0

[712 rows x 7 columns]

In [244]:
from sklearn.preprocessing import OneHotEncoder

trf2 = ColumnTransformer([

    ("ohe",
     OneHotEncoder(
         sparse_output=False,
         handle_unknown="ignore"
     ),
     [1,3])

], remainder="passthrough")

In [245]:
x_train_trf2=trf2.fit_transform(x_train_trf1)

In [246]:
x_train_trf2

array([[1.0, 0.0, 0.0, ..., 0, 2, 15.2458],
       [0.0, 0.0, 1.0, ..., 0, 0, 10.5],
       [1.0, 0.0, 0.0, ..., 1, 1, 37.0042],
       ...,
       [0.0, 1.0, 0.0, ..., 0, 0, 7.7333],
       [0.0, 0.0, 1.0, ..., 1, 0, 17.4],
       [0.0, 0.0, 1.0, ..., 1, 1, 39.0]], shape=(712, 10), dtype=object)

In [249]:
x_train_trf2=pd.DataFrame(x_train_trf2,columns=trf2.get_feature_names_out(),index=x_train_trf1.index)

In [250]:
x_train_trf2

,ohe__Embarked_C,ohe__Embarked_Q,ohe__Embarked_S,ohe__Sex_female,ohe__Sex_male,remainder__Age,remainder__Pclass,remainder__SibSp,remainder__Parch,remainder__Fare
140,1.0,0.0,0.0,1.0,0.0,29.745184,3,0,2,15.2458
439,0.0,0.0,1.0,0.0,1.0,31.0,2,0,0,10.5
817,1.0,0.0,0.0,0.0,1.0,31.0,2,1,1,37.0042
378,1.0,0.0,0.0,0.0,1.0,20.0,3,0,0,4.0125
491,0.0,0.0,1.0,0.0,1.0,21.0,3,0,0,7.25
...,...,...,...,...,...,...,...,...,...,...
835,1.0,0.0,0.0,1.0,0.0,39.0,1,1,1,83.1583
192,0.0,0.0,1.0,1.0,0.0,19.0,3,1,0,7.8542
629,0.0,1.0,0.0,0.0,1.0,29.745184,3,0,0,7.7333
559,0.0,0.0,1.0,1.0,0.0,36.0,3,1,0,17.4
684,0.0,0.0,1.0,0.0,1.0,60.0,2,1,1,39.0

In [253]:
x_train_trf2.isnull().sum()

ohe__Embarked_C      0
ohe__Embarked_Q      0
ohe__Embarked_S      0
ohe__Sex_female      0
ohe__Sex_male        0
remainder__Age       0
remainder__Pclass    0
remainder__SibSp     0
remainder__Parch     0
remainder__Fare      0
dtype: int64

In [255]:
x_train.head(2)

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
140       3  female   NaN      0      2  15.2458        C
439       2    male  31.0      0      0  10.5000        S

In [256]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

trf1 = ColumnTransformer([

    ("age_imputer",
     SimpleImputer(),
     ["Age"]),

    ("embarked_imputer",
     SimpleImputer(strategy="most_frequent"),
     ["Embarked"])

], remainder="passthrough")

In [257]:
from sklearn.preprocessing import OneHotEncoder

trf2 = ColumnTransformer([

    ("ohe",
     OneHotEncoder(
         sparse_output=False,
         handle_unknown="ignore"
     ),
     ["Sex","Embarked"])

], remainder="passthrough")

In [258]:
pipe = Pipeline([

    ("trf1", trf1),

    ("trf2", trf2)

])

In [259]:
pipe.fit_transform(x_train)

ValueError: Specifying the columns using strings is only supported for dataframes.

In [265]:
x_train.head(2)

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
140       3  female   NaN      0      2  15.2458        C
439       2    male  31.0      0      0  10.5000        S

In [276]:
trf1 = ColumnTransformer([

    ("age_imp",
     SimpleImputer(),
     ["Age"]),

    ("embarked_imp",
     SimpleImputer(strategy="most_frequent"),
     ["Embarked"])

], remainder="passthrough")

trf1.set_output(transform="pandas")

ColumnTransformer(remainder='passthrough',
                  transformers=[('age_imp', SimpleImputer(), ['Age']),
                                ('embarked_imp',
                                 SimpleImputer(strategy='most_frequent'),
                                 ['Embarked'])])

In [277]:
x_temp = trf1.fit_transform(x_train)

print(x_temp.columns)

Index(['age_imp__Age', 'embarked_imp__Embarked', 'remainder__Pclass',
       'remainder__Sex', 'remainder__SibSp', 'remainder__Parch',
       'remainder__Fare'],
      dtype='str')

In [278]:
trf2 = ColumnTransformer([

    ("ohe",
     OneHotEncoder(
         sparse_output=False,
         handle_unknown="ignore"
     ),
     ["remainder__Sex","embarked_imp__Embarked"])

], remainder="passthrough")

trf2.set_output(transform="pandas")

ColumnTransformer(remainder='passthrough',
                  transformers=[('ohe',
                                 OneHotEncoder(handle_unknown='ignore',
                                               sparse_output=False),
                                 ['remainder__Sex', 'embarked_imp__Embarked'])])

In [279]:
pipe = Pipeline([

    ("trf1", trf1),
    ("trf2", trf2)

])

In [280]:
pipe.fit_transform(x_train)

,ohe__remainder__Sex_female,ohe__remainder__Sex_male,ohe__embarked_imp__Embarked_C,ohe__embarked_imp__Embarked_Q,ohe__embarked_imp__Embarked_S,remainder__age_imp__Age,remainder__remainder__Pclass,remainder__remainder__SibSp,remainder__remainder__Parch,remainder__remainder__Fare
140,1.0,0.0,1.0,0.0,0.0,29.745184,3,0,2,15.2458
439,0.0,1.0,0.0,0.0,1.0,31.000000,2,0,0,10.5000
817,0.0,1.0,1.0,0.0,0.0,31.000000,2,1,1,37.0042
378,0.0,1.0,1.0,0.0,0.0,20.000000,3,0,0,4.0125
491,0.0,1.0,0.0,0.0,1.0,21.000000,3,0,0,7.2500
...,...,...,...,...,...,...,...,...,...,...
835,1.0,0.0,1.0,0.0,0.0,39.000000,1,1,1,83.1583
192,1.0,0.0,0.0,0.0,1.0,19.000000,3,1,0,7.8542
629,0.0,1.0,0.0,1.0,0.0,29.745184,3,0,0,7.7333
559,1.0,0.0,0.0,0.0,1.0,36.000000,3,1,0,17.4000
684,0.0,1.0,0.0,0.0,1.0,60.000000,2,1,1,39.0000

In [281]:
pipe.fit_transform(x_train).shape

(712, 10)

In [ ]:
trf=ColumnTransformer([("imputer_age",SimpleImputer(),["Age"]),
                       ("imputer_embarked",SimpleImputer(strategy="most_frequent"),["Embarked"]),
                       ("ohe_sex",OneHotEncoder(sparse_output=False,handle_unknown="ignore"),["Sex","Embarked"])
                       ],remainder="passthrough")

In [ ]:
pipe=Pipeline([("trf",trf)])