In [2]:
import pandas as pd

In [27]:
date=pd.read_csv("orders.csv")

In [28]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [29]:
date.shape

(1000, 4)

In [30]:
date.isnull().sum()

date          0
product_id    0
city_id       0
orders        0
dtype: int64

In [31]:
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   str
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), str(1)
memory usage: 31.4 KB

In [14]:
#here,the date column dtype is string -->convert it into datetime dtype ,
#because,if it is str we cannot use datetime functionality on date column.

In [32]:
date["date"]=pd.to_datetime(date["date"])

In [33]:
date.head()

        date  product_id  city_id  orders
0 2019-12-10        5628       25       3
1 2018-08-15        3646       14     157
2 2018-10-23        1859       25       1
3 2019-08-17        7292       25       1
4 2019-01-06        4344       25       3

In [34]:
date.info()
#Now date column dtype is datetime,now we can use datetime functionality.

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[us]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[us](1), int64(3)
memory usage: 31.4 KB

In [35]:
#Extract year

date["Year"]=date["date"].dt.year

In [36]:
date.head()

        date  product_id  city_id  orders  Year
0 2019-12-10        5628       25       3  2019
1 2018-08-15        3646       14     157  2018
2 2018-10-23        1859       25       1  2018
3 2019-08-17        7292       25       1  2019
4 2019-01-06        4344       25       3  2019

In [37]:
date=date.drop(columns=["product_id","city_id","orders"])

In [40]:
date.head()

        date  Year
0 2019-12-10  2019
1 2018-08-15  2018
2 2018-10-23  2018
3 2019-08-17  2019
4 2019-01-06  2019

In [43]:
date=date.rename(columns={"date":"Date"})

In [45]:
date.head()

        Date  Year
0 2019-12-10  2019
1 2018-08-15  2018
2 2018-10-23  2018
3 2019-08-17  2019
4 2019-01-06  2019

In [47]:
#Extract month

date["Month"]=date["Date"].dt.month

In [49]:
date.head()

        Date  Year  Month
0 2019-12-10  2019     12
1 2018-08-15  2018      8
2 2018-10-23  2018     10
3 2019-08-17  2019      8
4 2019-01-06  2019      1

In [51]:
#month name
date["Month_Name"]=date["Date"].dt.month_name()

In [53]:
date.head()

        Date  Year  Month Month_Name
0 2019-12-10  2019     12   December
1 2018-08-15  2018      8     August
2 2018-10-23  2018     10    October
3 2019-08-17  2019      8     August
4 2019-01-06  2019      1    January

In [54]:
#Extract day

date["Day"]=date["Date"].dt.day

In [55]:
date.head()

        Date  Year  Month Month_Name  Day
0 2019-12-10  2019     12   December   10
1 2018-08-15  2018      8     August   15
2 2018-10-23  2018     10    October   23
3 2019-08-17  2019      8     August   17
4 2019-01-06  2019      1    January    6

In [57]:
#day name

date["Day_Name"]=date["Date"].dt.day_name()

In [59]:
date

          Date  Year  Month Month_Name  Day   Day_Name
0   2019-12-10  2019     12   December   10    Tuesday
1   2018-08-15  2018      8     August   15  Wednesday
2   2018-10-23  2018     10    October   23    Tuesday
3   2019-08-17  2019      8     August   17   Saturday
4   2019-01-06  2019      1    January    6     Sunday
..         ...   ...    ...        ...  ...        ...
995 2018-10-08  2018     10    October    8     Monday
996 2018-12-06  2018     12   December    6   Thursday
997 2019-05-07  2019      5        May    7    Tuesday
998 2019-03-03  2019      3      March    3     Sunday
999 2019-10-15  2019     10    October   15    Tuesday

[1000 rows x 6 columns]

In [61]:
#Extract date_of_week

date["Date_dow"]=date["Date"].dt.day_of_week

In [63]:
date.head()

        Date  Year  Month Month_Name  Day   Day_Name  Date_dow
0 2019-12-10  2019     12   December   10    Tuesday         1
1 2018-08-15  2018      8     August   15  Wednesday         2
2 2018-10-23  2018     10    October   23    Tuesday         1
3 2019-08-17  2019      8     August   17   Saturday         5
4 2019-01-06  2019      1    January    6     Sunday         6

In [65]:
#is_weekend
import numpy as np
date["Date_Weekend"]=np.where(date["Day_Name"].isin(["Saturday","Sunday"]),1,0)

In [75]:
date.head()

,Date,Year,Month,Month_Name,Day,Day_Name,Date_dow,Date_Weekend,Week_Of_The_Year
0,2019-12-10,2019,12,December,10,Tuesday,1,0,1
1,2018-08-15,2018,8,August,15,Wednesday,2,0,2
2,2018-10-23,2018,10,October,23,Tuesday,1,0,1
3,2019-08-17,2019,8,August,17,Saturday,5,1,5
4,2019-01-06,2019,1,January,6,Sunday,6,1,6

In [78]:
date=date.drop(columns=["Week_Of_The_Year"])

In [80]:
date.head()

        Date  Year  Month Month_Name  Day   Day_Name  Date_dow  Date_Weekend
0 2019-12-10  2019     12   December   10    Tuesday         1             0
1 2018-08-15  2018      8     August   15  Wednesday         2             0
2 2018-10-23  2018     10    October   23    Tuesday         1             0
3 2019-08-17  2019      8     August   17   Saturday         5             1
4 2019-01-06  2019      1    January    6     Sunday         6             1

In [82]:
#Extract quarter

date["Quarter"]=date["Date"].dt.quarter

In [86]:
date.head()

,Date,Year,Month,Month_Name,Day,Day_Name,Date_dow,Date_Weekend,Quarter
0,2019-12-10,2019,12,December,10,Tuesday,1,0,4
1,2018-08-15,2018,8,August,15,Wednesday,2,0,3
2,2018-10-23,2018,10,October,23,Tuesday,1,0,4
3,2019-08-17,2019,8,August,17,Saturday,5,1,3
4,2019-01-06,2019,1,January,6,Sunday,6,1,1

In [88]:
#Extract semester

date["Semester"]=np.where(date["Quarter"].isin([1,2]),1,2)

In [89]:
date.head()

,Date,Year,Month,Month_Name,Day,Day_Name,Date_dow,Date_Weekend,Quarter,Semester
0,2019-12-10,2019,12,December,10,Tuesday,1,0,4,2
1,2018-08-15,2018,8,August,15,Wednesday,2,0,3,2
2,2018-10-23,2018,10,October,23,Tuesday,1,0,4,2
3,2019-08-17,2019,8,August,17,Saturday,5,1,3,2
4,2019-01-06,2019,1,January,6,Sunday,6,1,1,1