In [1]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv("cars.csv")

In [5]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [7]:
df.shape

(8128, 5)

In [9]:
df["brand"].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Kia                 4
Ambassador          4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [11]:
df["brand"].value_counts().shape

(32,)

In [13]:
df["fuel"].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [14]:
df["owner"].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [17]:
from sklearn.model_selection import train_test_split

x=df[["brand","km_driven","fuel","owner"]]
y=df["selling_price"]

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [18]:
x_train

           brand  km_driven    fuel         owner
3042     Hyundai      60000     LPG   First Owner
1520        Tata     150000  Diesel   Third Owner
2611     Hyundai     110000  Diesel  Second Owner
3544    Mahindra      28000  Diesel  Second Owner
4138      Maruti      15000  Petrol   First Owner
...          ...        ...     ...           ...
4931        Tata      70000  Diesel   Third Owner
3264        Ford     100000  Diesel  Second Owner
1653     Hyundai      90000  Petrol  Second Owner
2607  Volkswagen      90000  Diesel   First Owner
2732     Hyundai     110000  Petrol   First Owner

[6502 rows x 4 columns]

In [19]:
x_test

         brand  km_driven    fuel         owner
3558   Hyundai      40000  Diesel   First Owner
233   Mahindra      70000  Diesel   First Owner
7952    Maruti       5000  Petrol   First Owner
572     Maruti     120000  Petrol   Third Owner
6960     Lexus      20000  Petrol   First Owner
...        ...        ...     ...           ...
7576      Fiat     100000  Diesel   Third Owner
1484    Maruti     120000  Petrol   Third Owner
1881    Maruti      40000  Diesel   First Owner
4917   Hyundai       2350  Petrol   First Owner
5934   Hyundai      80000  Diesel  Second Owner

[1626 rows x 4 columns]

In [20]:
y_train

3042     375000
1520     150000
2611     459999
3544    1050000
4138     700000
         ...
4931     300000
3264     220000
1653     170000
2607     375000
2732     225000
Name: selling_price, Length: 6502, dtype: int64

In [22]:
from sklearn.preprocessing import OneHotEncoder

ohe=OneHotEncoder(sparse_output=False,dtype=int,drop="first")#sparse_output-->output will look normal array,drop-->multicollinearity problem,dtype-->change dummy_variable dtype.

#transform

x_train_transform=ohe.fit_transform(x_train[["fuel","owner"]])
x_test_transform=ohe.transform(x_test[["fuel","owner"]])

In [24]:
x_train_transform

array([[0, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]], shape=(6502, 7))

In [27]:
x_train_remain_data=x_train[["brand","km_driven"]]
x_test_remain_data=x_test[["brand","km_driven"]]

In [30]:
x_train_remain_data

           brand  km_driven
3042     Hyundai      60000
1520        Tata     150000
2611     Hyundai     110000
3544    Mahindra      28000
4138      Maruti      15000
...          ...        ...
4931        Tata      70000
3264        Ford     100000
1653     Hyundai      90000
2607  Volkswagen      90000
2732     Hyundai     110000

[6502 rows x 2 columns]

In [32]:
x_test_remain_data

         brand  km_driven
3558   Hyundai      40000
233   Mahindra      70000
7952    Maruti       5000
572     Maruti     120000
6960     Lexus      20000
...        ...        ...
7576      Fiat     100000
1484    Maruti     120000
1881    Maruti      40000
4917   Hyundai       2350
5934   Hyundai      80000

[1626 rows x 2 columns]

In [35]:
# now convert array format into dataframe
 
pd.DataFrame(x_train_transform,columns=ohe.get_feature_names_out(["fuel","owner"])).head(5)
#need to write index=x_train_remain_data,because if we ont use it ,df start from 0,1,2 etc

,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,0,1,0,0,0,0,0
1,1,0,0,0,0,0,1
2,1,0,0,0,1,0,0
3,1,0,0,0,1,0,0
4,0,0,1,0,0,0,0

In [37]:
x_train_transform_df=pd.DataFrame(x_train_transform,columns=ohe.get_feature_names_out(["fuel","owner"]),index=x_train_remain_data.index)
x_train_transform_df

,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
3042,0,1,0,0,0,0,0
1520,1,0,0,0,0,0,1
2611,1,0,0,0,1,0,0
3544,1,0,0,0,1,0,0
4138,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...
4931,1,0,0,0,0,0,1
3264,1,0,0,0,1,0,0
1653,0,0,1,0,1,0,0
2607,1,0,0,0,0,0,0
2732,0,0,1,0,0,0,0

In [39]:
x_test_transform_df=pd.DataFrame(x_test_transform,columns=ohe.get_feature_names_out(["fuel","owner"]),index=x_test_remain_data.index)
x_test_transform_df

,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
3558,1,0,0,0,0,0,0
233,1,0,0,0,0,0,0
7952,0,0,1,0,0,0,0
572,0,0,1,0,0,0,1
6960,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...
7576,1,0,0,0,0,0,1
1484,0,0,1,0,0,0,1
1881,1,0,0,0,0,0,0
4917,0,0,1,0,0,0,0
5934,1,0,0,0,1,0,0

In [40]:
#now concat remaining & new transform data

pd.concat([x_train_remain_data,x_train_transform_df],axis=1)

,brand,km_driven,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
3042,Hyundai,60000,0,1,0,0,0,0,0
1520,Tata,150000,1,0,0,0,0,0,1
2611,Hyundai,110000,1,0,0,0,1,0,0
3544,Mahindra,28000,1,0,0,0,1,0,0
4138,Maruti,15000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...
4931,Tata,70000,1,0,0,0,0,0,1
3264,Ford,100000,1,0,0,0,1,0,0
1653,Hyundai,90000,0,0,1,0,1,0,0
2607,Volkswagen,90000,1,0,0,0,0,0,0
2732,Hyundai,110000,0,0,1,0,0,0,0

In [41]:
pd.concat([x_test_remain_data,x_test_transform_df],axis=1)

,brand,km_driven,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
3558,Hyundai,40000,1,0,0,0,0,0,0
233,Mahindra,70000,1,0,0,0,0,0,0
7952,Maruti,5000,0,0,1,0,0,0,0
572,Maruti,120000,0,0,1,0,0,0,1
6960,Lexus,20000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...
7576,Fiat,100000,1,0,0,0,0,0,1
1484,Maruti,120000,0,0,1,0,0,0,1
1881,Maruti,40000,1,0,0,0,0,0,0
4917,Hyundai,2350,0,0,1,0,0,0,0
5934,Hyundai,80000,1,0,0,0,1,0,0