In [1]:
import pandas as pd

In [8]:
#BASIC EXAMPLE 

import pandas as pd

df = pd.DataFrame({

    "Marks":[
        20,25,30,35,40,
        45,50,55,60,65,
        70,75,80,85,90
    ]

})

print(df)

    Marks
0      20
1      25
2      30
3      35
4      40
5      45
6      50
7      55
8      60
9      65
10     70
11     75
12     80
13     85
14     90

In [9]:
df.ndim

2

In [5]:
# condition:below 35 fail-->0 above 35 pass-->1

In [7]:
from sklearn.preprocessing import Binarizer

b=Binarizer(threshold=35)

In [11]:
binarizer_transformed=b.fit_transform(df[["Marks"]])

In [13]:
binarizer_transformed

array([[0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [16]:
pd.DataFrame(binarizer_transformed,columns=df.columns)

    Marks
0       0
1       0
2       0
3       0
4       1
5       1
6       1
7       1
8       1
9       1
10      1
11      1
12      1
13      1
14      1

In [17]:
df

    Marks
0      20
1      25
2      30
3      35
4      40
5      45
6      50
7      55
8      60
9      65
10     70
11     75
12     80
13     85
14     90