In [1]:
import pandas as pd

In [ ]:
# binarization def: converting numerical data into 0 & 1

In [19]:
#BASIC EXAMPLE 

import pandas as pd

df = pd.DataFrame({

    "Marks":[
        20,25,30,35,40,
        45,50,55,60,65,
        70,75,80,85,90
    ]

})

print(df)

    Marks
0      20
1      25
2      30
3      35
4      40
5      45
6      50
7      55
8      60
9      65
10     70
11     75
12     80
13     85
14     90

In [9]:
df.ndim

2

In [5]:
# condition:below 35 fail-->0 above 35 pass-->1

In [7]:
from sklearn.preprocessing import Binarizer

b=Binarizer(threshold=35)

In [11]:
binarizer_transformed=b.fit_transform(df[["Marks"]])

In [13]:
binarizer_transformed

array([[0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [16]:
pd.DataFrame(binarizer_transformed,columns=df.columns)

    Marks
0       0
1       0
2       0
3       0
4       1
5       1
6       1
7       1
8       1
9       1
10      1
11      1
12      1
13      1
14      1

In [17]:
df

    Marks
0      20
1      25
2      30
3      35
4      40
5      45
6      50
7      55
8      60
9      65
10     70
11     75
12     80
13     85
14     90

In [20]:
#2 example

In [22]:
import pandas as pd

df = pd.DataFrame({

    "Age":[
        20,22,24,26,28,30,32,34,36,38,
        40,42,44,46,48,50,52,54,56,58,
        60,62,64,66,68,70,72,74,76,78
    ],

    "BMI":[
        18,19,20,21,22,23,24,25,26,27,
        28,29,30,31,32,33,34,35,36,37,
        38,39,40,41,42,43,44,45,46,47
    ],

    "ExerciseHours":[
        8,8,7,7,6,6,5,5,4,4,
        4,3,3,3,2,2,2,1,1,1,
        1,0,0,0,0,0,0,0,0,0
    ],

    "Smoking":[
        0,0,0,0,0,0,1,1,0,0,
        1,0,1,0,1,1,0,0,1,0,
        1,1,0,1,0,1,1,0,1,1
    ],

    "MedicalCost":[
        2000,2300,2500,2800,3000,3500,4000,4500,5000,5500,
        6000,6500,7000,8000,9000,10000,11000,12000,13000,14500,
        16000,17500,19000,21000,23000,25000,27000,29000,31000,33000
    ]

})

df.to_csv("hospital.csv",index=False)

In [25]:
df.head()

   Age  BMI  ExerciseHours  Smoking  MedicalCost
0   20   18              8        0         2000
1   22   19              8        0         2300
2   24   20              7        0         2500
3   26   21              7        0         2800
4   28   22              6        0         3000

In [27]:
df.shape

(30, 5)

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
x = df.drop(columns=["MedicalCost"])
y=df[["MedicalCost"]] #MedicalCost = number ,Regression problem 😄

In [34]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [37]:
x_train.head()

    Age  BMI  ExerciseHours  Smoking
27   74   45              0        0
11   42   29              3        0
17   54   35              1        0
22   64   40              0        0
5    30   23              6        0

In [40]:
x_train.shape

(24, 4)

In [42]:
x_test.shape

(6, 4)

In [43]:

# Apply Binarization on ONE feature 😄
# Let's do on:

# BMI 😄
#BMI >= 30
# → unhealthy 😄

In [45]:
x_train.head(2)

    Age  BMI  ExerciseHours  Smoking
27   74   45              0        0
11   42   29              3        0

In [ ]:
from sklearn.preprocessing import Binarizer

bin=Binarizer(threshold=30)  #below 30 → 0 ,30 or above → 1

In [47]:
x_train_bin=bin.fit_transform(x_train[["BMI"]])
x_test_bin=bin.transform(x_test[["BMI"]])

In [49]:
x_train_bin

array([[1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0]])

In [56]:
pd.DataFrame(x_train_bin,columns=bin.get_feature_names_out(),index=x_train.index).head(4)

    BMI
27    1
11    0
17    1
22    1

In [57]:
x_train

    Age  BMI  ExerciseHours  Smoking
27   74   45              0        0
11   42   29              3        0
17   54   35              1        0
22   64   40              0        0
5    30   23              6        0
16   52   34              2        0
8    36   26              4        0
14   48   32              2        1
23   66   41              0        1
20   60   38              1        1
1    22   19              8        0
29   78   47              0        1
6    32   24              5        1
4    28   22              6        0
18   56   36              1        1
19   58   37              1        0
9    38   27              4        0
7    34   25              5        1
25   70   43              0        1
3    26   21              7        0
0    20   18              8        0
21   62   39              0        1
15   50   33              2        1
12   44   30              3        1

In [54]:
pd.DataFrame(x_test_bin,columns=bin.get_feature_names_out(),index=x_test.index)

    BMI
2     0
28    1
13    1
10    0
26    1
24    1