In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm
import pandas as pd

In [36]:
#equal width binning (uniform binning)

In [56]:
import pandas as pd

df = pd.DataFrame({

    "Age":[
        18,20,22,24,26,28,30,32,34,36,
        38,40,42,44,46,48,50,52,54,56,
        58,60,62,64,66,68,70,72,74,76
    ],

    "BMI":[
        18,19,20,21,22,23,24,25,26,27,
        28,29,30,31,32,33,34,35,36,37,
        38,39,40,41,42,43,44,45,46,47
    ],

    "Smoking":[
        0,0,0,0,0,0,1,1,0,0,
        1,0,1,0,1,1,0,0,1,0,
        1,1,0,1,0,1,1,0,1,1
    ],

    "ExerciseHours":[
        8,8,7,7,6,6,5,5,5,4,
        4,4,3,3,3,2,2,2,1,1,
        1,1,0,0,0,0,0,0,0,0
    ],

    "MedicalCost":[
        2000,2200,2400,2600,2800,3000,3500,4000,4200,4500,
        5000,5500,6000,6800,7500,8200,9000,10000,11000,12500,
        14000,15500,17000,18500,20000,22000,24000,26000,28000,30000
    ]
})

df.to_csv("health_data.csv", index=False)

In [57]:
df.head()

   Age  BMI  Smoking  ExerciseHours  MedicalCost
0   18   18        0              8         2000
1   20   19        0              8         2200
2   22   20        0              7         2400
3   24   21        0              7         2600
4   26   22        0              6         2800

In [58]:
x = df.drop(columns=["MedicalCost"])
y = df[["MedicalCost"]]

In [59]:
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [68]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
dt=DecisionTreeClassifier()

In [67]:

x_train.head()

    Age  BMI  Smoking  ExerciseHours
28   74   46        1              0
24   66   42        0              0
12   42   30        1              3
0    18   18        0              8
4    26   22        0              6

In [70]:
x_train.head()

    Age  BMI  Smoking  ExerciseHours
28   74   46        1              0
24   66   42        0              0
12   42   30        1              3
0    18   18        0              8
4    26   22        0              6

In [71]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import KBinsDiscretizer
kbin_age=KBinsDiscretizer(n_bins=5, encode="ordinal", strategy="uniform")
kbin_bmi=KBinsDiscretizer(n_bins=5, encode="ordinal", strategy="uniform")

In [73]:
trf=ColumnTransformer([
    ("first",kbin_age,[0]),
    ("second",kbin_bmi,[1])],remainder="passthrough")

In [76]:
x_train_trf=trf.fit_transform(x_train)
x_test_trf=trf.transform(x_test)

In [79]:
trf.get_feature_names_out()

array(['first__Age', 'second__BMI', 'remainder__Smoking',
       'remainder__ExerciseHours'], dtype=object)

In [82]:
pd.DataFrame(x_train_trf, columns=trf.get_feature_names_out()).head()

   first__Age  second__BMI  remainder__Smoking  remainder__ExerciseHours
0         4.0          4.0                 1.0                       0.0
1         4.0          4.0                 0.0                       0.0
2         2.0          2.0                 1.0                       3.0
3         0.0          0.0                 0.0                       8.0
4         0.0          0.0                 0.0                       6.0

In [87]:
trf.named_transformers_["first"].bin_edges_

array([array([18. , 29.6, 41.2, 52.8, 64.4, 76. ])], dtype=object)

In [91]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [92]:
# Models
lr = LinearRegression()
lr2 = LinearRegression()

# without binning
lr.fit(x_train, y_train)

# with equal width binning
lr2.fit(x_train_trf, y_train)

# prediction
y_pred = lr.predict(x_test)

y_pred2 = lr2.predict(x_test_trf)

# R2 score
print(
    "Without Binning:",
    r2_score(y_test, y_pred)
)

print(
    "With Equal Width Binning:",
    r2_score(y_test, y_pred2)
)

Without Binning: 0.9696445635003152
With Equal Width Binning: 0.9082097873856014