In [1]:
import pandas as pd

In [34]:
df=pd.read_csv("titanic.csv",usecols=["Name","Sex","Embarked"])

In [35]:
df.head(2)

                                                Name     Sex Embarked
0                            Braund, Mr. Owen Harris    male        S
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female        C

In [36]:
df.isnull().sum()

Name        0
Sex         0
Embarked    2
dtype: int64

In [37]:
df["Embarked"]=df["Embarked"].fillna("C")

In [38]:
df.head()

                                                Name     Sex Embarked
0                            Braund, Mr. Owen Harris    male        S
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female        C
2                             Heikkinen, Miss. Laina  female        S
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female        S
4                           Allen, Mr. William Henry    male        S

In [39]:
df.isnull().sum()

Name        0
Sex         0
Embarked    0
dtype: int64

In [15]:
#working on name columns-->split it inti title firstname,lastname

In [17]:
#lastname and rest

In [40]:
df[["LastName","Rest"]]=df["Name"].str.split(",",expand=True)

In [41]:
df.head()

,Name,Sex,Embarked,LastName,Rest
0,"Braund, Mr. Owen Harris",male,S,Braund,Mr. Owen Harris
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,C,Cumings,Mrs. John Bradley (Florence Briggs Thayer)
2,"Heikkinen, Miss. Laina",female,S,Heikkinen,Miss. Laina
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,S,Futrelle,Mrs. Jacques Heath (Lily May Peel)
4,"Allen, Mr. William Henry",male,S,Allen,Mr. William Henry

In [42]:
df["Title"]=df["Rest"].str.extract(r"([A-Za-z]+)\.")

In [43]:
df.head()

,Name,Sex,Embarked,LastName,Rest,Title
0,"Braund, Mr. Owen Harris",male,S,Braund,Mr. Owen Harris,Mr
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,C,Cumings,Mrs. John Bradley (Florence Briggs Thayer),Mrs
2,"Heikkinen, Miss. Laina",female,S,Heikkinen,Miss. Laina,Miss
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,S,Futrelle,Mrs. Jacques Heath (Lily May Peel),Mrs
4,"Allen, Mr. William Henry",male,S,Allen,Mr. William Henry,Mr

In [44]:
df["FirstName"]=df["Rest"].str.replace(r"([A-Za-z]+)\.","",regex=True).str.split()

In [45]:
df.head()

,Name,Sex,Embarked,LastName,Rest,Title,FirstName
0,"Braund, Mr. Owen Harris",male,S,Braund,Mr. Owen Harris,Mr,"[Owen, Harris]"
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,C,Cumings,Mrs. John Bradley (Florence Briggs Thayer),Mrs,"[John, Bradley, (Florence, Briggs, Thayer)]"
2,"Heikkinen, Miss. Laina",female,S,Heikkinen,Miss. Laina,Miss,[Laina]
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,S,Futrelle,Mrs. Jacques Heath (Lily May Peel),Mrs,"[Jacques, Heath, (Lily, May, Peel)]"
4,"Allen, Mr. William Henry",male,S,Allen,Mr. William Henry,Mr,"[William, Henry]"

In [50]:
df["FirstName_modify"]=df["Rest"].str.replace(r"([A-Za-z]+)\.","",regex=True).str.replace(","," ")

In [51]:
df.head()

,Name,Sex,Embarked,LastName,Rest,Title,FirstName,FirstName_modify
0,"Braund, Mr. Owen Harris",male,S,Braund,Mr. Owen Harris,Mr,"[Owen, Harris]",Owen Harris
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,C,Cumings,Mrs. John Bradley (Florence Briggs Thayer),Mrs,"[John, Bradley, (Florence, Briggs, Thayer)]",John Bradley (Florence Briggs Thayer)
2,"Heikkinen, Miss. Laina",female,S,Heikkinen,Miss. Laina,Miss,[Laina],Laina
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,S,Futrelle,Mrs. Jacques Heath (Lily May Peel),Mrs,"[Jacques, Heath, (Lily, May, Peel)]",Jacques Heath (Lily May Peel)
4,"Allen, Mr. William Henry",male,S,Allen,Mr. William Henry,Mr,"[William, Henry]",William Henry

In [52]:
import pandas as pd

# Sample dataset
df = pd.DataFrame({
    "Name": [
        "John Michael Smith",
        "Emma Watson",
        "Robert Downey Jr"
    ]
})

print("📦 ORIGINAL DATA")
print(df)

📦 ORIGINAL DATA
                 Name
0  John Michael Smith
1         Emma Watson
2    Robert Downey Jr

In [56]:
df[["FirstName","MiddleName","LastName"]]=df["Name"].str.split(expand=True)

In [57]:
print("\n👤 AFTER FEATURE SPLITTING")
print(df)

👤 AFTER FEATURE SPLITTING
                 Name FirstName MiddleName LastName
0  John Michael Smith      John    Michael    Smith
1         Emma Watson      Emma     Watson      NaN
2    Robert Downey Jr    Robert     Downey       Jr