In [18]:
import pandas as pd
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [3]:
df=pd.read_csv("titanic.csv",usecols=["Age","Pclass","SibSp","Parch","Survived"])

In [5]:
df.head()

   Survived  Pclass   Age  SibSp  Parch
0         0       3  22.0      1      0
1         1       1  38.0      1      0
2         1       3  26.0      0      0
3         1       1  35.0      1      0
4         0       3  35.0      0      0

In [7]:
df.isnull().sum()

Survived      0
Pclass        0
Age         177
SibSp         0
Parch         0
dtype: int64

In [9]:
df=df.dropna()

In [11]:
df.head()

   Survived  Pclass   Age  SibSp  Parch
0         0       3  22.0      1      0
1         1       1  38.0      1      0
2         1       3  26.0      0      0
3         1       1  35.0      1      0
4         0       3  35.0      0      0

In [13]:
df.isnull().sum()

Survived    0
Pclass      0
Age         0
SibSp       0
Parch       0
dtype: int64

In [15]:
x=df.drop(columns=["Survived"])
y=df["Survived"]

In [19]:
np.mean((cross_val_score(LogisticRegression(),x,y,scoring="accuracy",cv=20)))

np.float64(0.6933333333333332)

In [21]:
#Apply feature Construction

In [28]:
df["Family_size"]=df["SibSp"] + df["Parch"] +1

In [29]:
df.head()

   Survived  Pclass   Age  SibSp  Parch  Family_size
0         0       3  22.0      1      0            2
1         1       1  38.0      1      0            2
2         1       3  26.0      0      0            1
3         1       1  35.0      1      0            2
4         0       3  35.0      0      0            1

In [31]:
df=df.drop(columns=["SibSp","Parch"])

In [32]:
df.head(2)

   Survived  Pclass   Age  Family_size
0         0       3  22.0            2
1         1       1  38.0            2

In [33]:
x=df.drop(columns=["Survived"])
y=df["Survived"]

In [34]:
np.mean(cross_val_score(LogisticRegression(),x,y,scoring="accuracy",cv=20))

np.float64(0.6919444444444444)

In [36]:
#example2

In [38]:
import pandas as pd

df = pd.DataFrame({
    "Product": ["Wireless Mouse", "Gaming Keyboard", "Headphones", "Mobile Charger"],
    "Price": [1000, 2000, 1500, 800],
    "Discount": [20, 10, 15, 5]
})



print(df)

           Product  Price  Discount
0   Wireless Mouse   1000        20
1  Gaming Keyboard   2000        10
2       Headphones   1500        15
3   Mobile Charger    800         5

In [ ]:
# Feature Construction: Final Price
    
    
df["FinalPrice"] = df["Price"] - (df["Price"] * df["Discount"] / 100)

In [40]:
df.head()

           Product  Price  Discount  FinalPrice
0   Wireless Mouse   1000        20       800.0
1  Gaming Keyboard   2000        10      1800.0
2       Headphones   1500        15      1275.0
3   Mobile Charger    800         5       760.0