In [ ]:
# from sklearn.experimental import enable_iterative_imputer--->MEANS:The feature is still under testing.
# The developers may change it in future versions.
# "Use it, but be aware that we may modify it later."

In [1]:
import pandas as pd
import numpy as np

In [21]:
df = pd.DataFrame({
    "Age":[25,30,np.nan,40,45,50,35,28],
    "Salary":[30000,40000,50000,np.nan,80000,90000,60000,35000],
    "Experience":[2,5,8,10,15,20,7,3],
    "Purchased":[0,0,0,1,1,1,0,0]
})

print(df)

    Age   Salary  Experience  Purchased
0  25.0  30000.0           2          0
1  30.0  40000.0           5          0
2   NaN  50000.0           8          0
3  40.0      NaN          10          1
4  45.0  80000.0          15          1
5  50.0  90000.0          20          1
6  35.0  60000.0           7          0
7  28.0  35000.0           3          0

In [5]:
from sklearn.model_selection import train_test_split

In [7]:
x=df.drop(columns=["Purchased"])
y=df["Purchased"]

In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [12]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression

In [14]:
imputer=IterativeImputer(random_state=42)
x_train_imputed=imputer.fit_transform(x_train)
x_test_imputed=imputer.transform(x_test)

In [23]:
df

    Age   Salary  Experience  Purchased
0  25.0  30000.0           2          0
1  30.0  40000.0           5          0
2   NaN  50000.0           8          0
3  40.0      NaN          10          1
4  45.0  80000.0          15          1
5  50.0  90000.0          20          1
6  35.0  60000.0           7          0
7  28.0  35000.0           3          0

In [22]:
pd.DataFrame(x_train_imputed,columns=x_train.columns,index=x_train.index)

         Age        Salary  Experience
0  25.000000  30000.000000         2.0
7  28.000000  35000.000000         3.0
2  32.791424  50000.000000         8.0
4  45.000000  80000.000000        15.0
3  40.000000  68853.077208        10.0
6  35.000000  60000.000000         7.0

In [19]:
lr=LogisticRegression(max_iter=1000,random_state=42)
lr.fit(x_train_imputed,y_train)

y_pred=lr.predict(x_test_imputed)
print("Accuracy:",accuracy_score(y_test,y_pred))

Accuracy: 1.0