In [2]:
import pandas as pd

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

In [5]:
#LOAD DATASET

In [33]:
index_number_titanic=pd.read_csv("index_number_titanic.csv")

In [9]:
index_number_titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [11]:
index_number_titanic.shape

(891, 12)

In [13]:
index_number_titanic.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [15]:
df=index_number_titanic[["Survived","Pclass","Sex","Age","SibSp","Parch","Fare","Embarked"]]

In [17]:
df

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [19]:
#filled missing value in age and embarked column
#age-->mean,embarked-->most_frequent

In [21]:
x=df.drop("Survived",axis=1)
y=df[["Survived"]]

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [23]:
x_train

     Pclass     Sex   Age  SibSp  Parch      Fare Embarked
331       1    male  45.5      0      0   28.5000        S
733       2    male  23.0      0      0   13.0000        S
382       3    male  32.0      0      0    7.9250        S
704       3    male  26.0      1      0    7.8542        S
813       3  female   6.0      4      2   31.2750        S
..      ...     ...   ...    ...    ...       ...      ...
106       3  female  21.0      0      0    7.6500        S
270       1    male   NaN      0      0   31.0000        S
860       3    male  41.0      2      0   14.1083        S
435       1  female  14.0      1      2  120.0000        S
102       1    male  21.0      0      1   77.2875        S

[712 rows x 7 columns]

In [25]:
y_train

     Survived
331         0
733         0
382         0
704         0
813         0
..        ...
106         1
270         0
860         0
435         1
102         0

[712 rows x 1 columns]

In [27]:
x_train.head(3)

     Pclass   Sex   Age  SibSp  Parch    Fare Embarked
331       1  male  45.5      0      0  28.500        S
733       2  male  23.0      0      0  13.000        S
382       3  male  32.0      0      0   7.925        S

In [ ]:
#CASE-1

In [28]:
trf=ColumnTransformer([("age_imp",SimpleImputer(),[2]),
                       ("embarked_imp",SimpleImputer(strategy="most_frequent"),[6]),
                       ("ohe_sex_embarked",OneHotEncoder(sparse_output=False,handle_unknown="ignore"),[1,6])],remainder="passthrough")

In [30]:
pipe=Pipeline([("trf",trf)])

In [31]:
pipe.fit_transform(x_train)

array([[45.5, 'S', 0.0, ..., 0.0, 0.0, 28.5],
       [23.0, 'S', 0.0, ..., 0.0, 0.0, 13.0],
       [32.0, 'S', 0.0, ..., 0.0, 0.0, 7.925],
       ...,
       [41.0, 'S', 0.0, ..., 2.0, 0.0, 14.1083],
       [14.0, 'S', 1.0, ..., 1.0, 2.0, 120.0],
       [21.0, 'S', 0.0, ..., 0.0, 1.0, 77.2875]],
      shape=(712, 12), dtype=object)

In [32]:
pipe.get_feature_names_out()

array(['age_imp__Age', 'embarked_imp__Embarked',
       'ohe_sex_embarked__Sex_female', 'ohe_sex_embarked__Sex_male',
       'ohe_sex_embarked__Embarked_C', 'ohe_sex_embarked__Embarked_Q',
       'ohe_sex_embarked__Embarked_S', 'ohe_sex_embarked__Embarked_nan',
       'remainder__Pclass', 'remainder__SibSp', 'remainder__Parch',
       'remainder__Fare'], dtype=object)

In [ ]:
#CASE-2

In [35]:
df1=index_number_titanic[["Survived","Pclass","Sex","Age","SibSp","Parch","Fare","Embarked"]]

In [36]:
df1

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [37]:
x=df1.drop("Survived",axis=1)
y=df1[["Survived"]]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [38]:
x_train.head()

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
331       1    male  45.5      0      0  28.5000        S
733       2    male  23.0      0      0  13.0000        S
382       3    male  32.0      0      0   7.9250        S
704       3    male  26.0      1      0   7.8542        S
813       3  female   6.0      4      2  31.2750        S

In [39]:
embarked_pipe=Pipeline([("emb_imp",SimpleImputer(strategy="most_frequent")),
                        ("emb_ohe",OneHotEncoder(sparse_output=False,handle_unknown="ignore"))])

In [40]:
trf=ColumnTransformer([("age_imp",SimpleImputer(),[2]),
                       ("ohe_sex",OneHotEncoder(sparse_output=False,handle_unknown="ignore"),[1]),
                       ("ohe_imp_embarked",embarked_pipe,[6])],remainder="passthrough")

In [42]:
pipe=Pipeline([("trf",trf)])

In [44]:
pipe.fit_transform(x_train)

array([[ 45.5   ,   0.    ,   1.    , ...,   0.    ,   0.    ,  28.5   ],
       [ 23.    ,   0.    ,   1.    , ...,   0.    ,   0.    ,  13.    ],
       [ 32.    ,   0.    ,   1.    , ...,   0.    ,   0.    ,   7.925 ],
       ...,
       [ 41.    ,   0.    ,   1.    , ...,   2.    ,   0.    ,  14.1083],
       [ 14.    ,   1.    ,   0.    , ...,   1.    ,   2.    , 120.    ],
       [ 21.    ,   0.    ,   1.    , ...,   0.    ,   1.    ,  77.2875]],
      shape=(712, 10))

In [46]:
pipe.get_feature_names_out()

array(['age_imp__Age', 'ohe_sex__Sex_female', 'ohe_sex__Sex_male',
       'ohe_imp_embarked__Embarked_C', 'ohe_imp_embarked__Embarked_Q',
       'ohe_imp_embarked__Embarked_S', 'remainder__Pclass',
       'remainder__SibSp', 'remainder__Parch', 'remainder__Fare'],
      dtype=object)

In [47]:
pd.DataFrame(pipe.fit_transform(x_train),columns=pipe.get_feature_names_out())

,age_imp__Age,ohe_sex__Sex_female,ohe_sex__Sex_male,ohe_imp_embarked__Embarked_C,ohe_imp_embarked__Embarked_Q,ohe_imp_embarked__Embarked_S,remainder__Pclass,remainder__SibSp,remainder__Parch,remainder__Fare
0,45.500000,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,28.5000
1,23.000000,0.0,1.0,0.0,0.0,1.0,2.0,0.0,0.0,13.0000
2,32.000000,0.0,1.0,0.0,0.0,1.0,3.0,0.0,0.0,7.9250
3,26.000000,0.0,1.0,0.0,0.0,1.0,3.0,1.0,0.0,7.8542
4,6.000000,1.0,0.0,0.0,0.0,1.0,3.0,4.0,2.0,31.2750
...,...,...,...,...,...,...,...,...,...,...
707,21.000000,1.0,0.0,0.0,0.0,1.0,3.0,0.0,0.0,7.6500
708,29.498846,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,31.0000
709,41.000000,0.0,1.0,0.0,0.0,1.0,3.0,2.0,0.0,14.1083
710,14.000000,1.0,0.0,0.0,0.0,1.0,1.0,1.0,2.0,120.0000
711,21.000000,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,77.2875

In [48]:
pd.DataFrame(pipe.fit_transform(x_train),columns=pipe.get_feature_names_out(),index=x_train.index)

,age_imp__Age,ohe_sex__Sex_female,ohe_sex__Sex_male,ohe_imp_embarked__Embarked_C,ohe_imp_embarked__Embarked_Q,ohe_imp_embarked__Embarked_S,remainder__Pclass,remainder__SibSp,remainder__Parch,remainder__Fare
331,45.500000,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,28.5000
733,23.000000,0.0,1.0,0.0,0.0,1.0,2.0,0.0,0.0,13.0000
382,32.000000,0.0,1.0,0.0,0.0,1.0,3.0,0.0,0.0,7.9250
704,26.000000,0.0,1.0,0.0,0.0,1.0,3.0,1.0,0.0,7.8542
813,6.000000,1.0,0.0,0.0,0.0,1.0,3.0,4.0,2.0,31.2750
...,...,...,...,...,...,...,...,...,...,...
106,21.000000,1.0,0.0,0.0,0.0,1.0,3.0,0.0,0.0,7.6500
270,29.498846,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,31.0000
860,41.000000,0.0,1.0,0.0,0.0,1.0,3.0,2.0,0.0,14.1083
435,14.000000,1.0,0.0,0.0,0.0,1.0,1.0,1.0,2.0,120.0000
102,21.000000,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,77.2875