In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

In [13]:
index_number_titanic=pd.read_csv("index_number_titanic.csv")

In [14]:
index_number_titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [15]:
index_number_titanic.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [17]:
df=index_number_titanic[["Survived","Pclass","Sex","Age","SibSp","Parch","Fare","Embarked"]]

In [19]:
df

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [21]:
x=df.drop("Survived",axis=1)
y=df[["Survived"]]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [26]:
x_train.head()

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
331       1    male  45.5      0      0  28.5000        S
733       2    male  23.0      0      0  13.0000        S
382       3    male  32.0      0      0   7.9250        S
704       3    male  26.0      1      0   7.8542        S
813       3  female   6.0      4      2  31.2750        S

In [25]:
trf1=ColumnTransformer([("age_imp",SimpleImputer(),[2]),
                        ("embarked_imp",SimpleImputer(strategy="most_frequent"),[6])],remainder="passthrough")

In [28]:
trf2=ColumnTransformer([("ohe_sex_embarked",OneHotEncoder(sparse_output=False,handle_unknown="ignore"),[1,6])],remainder="passthrough")

In [30]:
pipe=Pipeline([("trf1",trf1),
               ("trf2",trf2)])

In [31]:
pipe.fit_transform(x_train)

array([[0.0, 0.0, 1.0, ..., 'male', 0, 0],
       [0.0, 0.0, 1.0, ..., 'male', 0, 0],
       [0.0, 0.0, 1.0, ..., 'male', 0, 0],
       ...,
       [0.0, 0.0, 1.0, ..., 'male', 2, 0],
       [0.0, 0.0, 1.0, ..., 'female', 1, 2],
       [0.0, 0.0, 1.0, ..., 'male', 0, 1]], shape=(712, 228), dtype=object)

In [32]:
x_train.head()

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
331       1    male  45.5      0      0  28.5000        S
733       2    male  23.0      0      0  13.0000        S
382       3    male  32.0      0      0   7.9250        S
704       3    male  26.0      1      0   7.8542        S
813       3  female   6.0      4      2  31.2750        S

In [ ]:
trf1=ColumnTransformer([("age_imp",SimpleImputer(),[2]),
                        ("embarked_imp",SimpleImputer(strategy="most_frequent"),[6])],remainder="passthrough")

In [ ]:
#internally its change the column index after transformation so we have to change the column index for trf2

In [35]:
# trf1.fit_transform(x_train) #to check the transformer change.

In [36]:
trf1.fit_transform(x_train)

array([[45.5, 'S', 1, ..., 0, 0, 28.5],
       [23.0, 'S', 2, ..., 0, 0, 13.0],
       [32.0, 'S', 3, ..., 0, 0, 7.925],
       ...,
       [41.0, 'S', 3, ..., 2, 0, 14.1083],
       [14.0, 'S', 1, ..., 1, 2, 120.0],
       [21.0, 'S', 1, ..., 0, 1, 77.2875]], shape=(712, 7), dtype=object)

In [38]:
trf1.get_feature_names_out()

array(['age_imp__Age', 'embarked_imp__Embarked', 'remainder__Pclass',
       'remainder__Sex', 'remainder__SibSp', 'remainder__Parch',
       'remainder__Fare'], dtype=object)

In [40]:
trf2=ColumnTransformer([("ohe_emb_sex",OneHotEncoder(sparse_output=False,handle_unknown="ignore"),[1,3])],remainder="passthrough")

In [42]:
pipeline=Pipeline([("trf1",trf1),
                   ("trf2",trf2)])

In [44]:
pipeline.fit_transform(x_train)

array([[0.0, 0.0, 1.0, ..., 0, 0, 28.5],
       [0.0, 0.0, 1.0, ..., 0, 0, 13.0],
       [0.0, 0.0, 1.0, ..., 0, 0, 7.925],
       ...,
       [0.0, 0.0, 1.0, ..., 2, 0, 14.1083],
       [0.0, 0.0, 1.0, ..., 1, 2, 120.0],
       [0.0, 0.0, 1.0, ..., 0, 1, 77.2875]], shape=(712, 10), dtype=object)

In [47]:
pipeline.get_feature_names_out()

array(['ohe_emb_sex__embarked_imp__Embarked_C',
       'ohe_emb_sex__embarked_imp__Embarked_Q',
       'ohe_emb_sex__embarked_imp__Embarked_S',
       'ohe_emb_sex__remainder__Sex_female',
       'ohe_emb_sex__remainder__Sex_male', 'remainder__age_imp__Age',
       'remainder__remainder__Pclass', 'remainder__remainder__SibSp',
       'remainder__remainder__Parch', 'remainder__remainder__Fare'],
      dtype=object)

In [49]:
pd.DataFrame(pipeline.fit_transform(x_train),columns=pipeline.get_feature_names_out(),index=x_train.index)

,ohe_emb_sex__embarked_imp__Embarked_C,ohe_emb_sex__embarked_imp__Embarked_Q,ohe_emb_sex__embarked_imp__Embarked_S,ohe_emb_sex__remainder__Sex_female,ohe_emb_sex__remainder__Sex_male,remainder__age_imp__Age,remainder__remainder__Pclass,remainder__remainder__SibSp,remainder__remainder__Parch,remainder__remainder__Fare
331,0.0,0.0,1.0,0.0,1.0,45.5,1,0,0,28.5
733,0.0,0.0,1.0,0.0,1.0,23.0,2,0,0,13.0
382,0.0,0.0,1.0,0.0,1.0,32.0,3,0,0,7.925
704,0.0,0.0,1.0,0.0,1.0,26.0,3,1,0,7.8542
813,0.0,0.0,1.0,1.0,0.0,6.0,3,4,2,31.275
...,...,...,...,...,...,...,...,...,...,...
106,0.0,0.0,1.0,1.0,0.0,21.0,3,0,0,7.65
270,0.0,0.0,1.0,0.0,1.0,29.498846,1,0,0,31.0
860,0.0,0.0,1.0,0.0,1.0,41.0,3,2,0,14.1083
435,0.0,0.0,1.0,1.0,0.0,14.0,1,1,2,120.0
102,0.0,0.0,1.0,0.0,1.0,21.0,1,0,1,77.2875