In [1]:
import pandas as pd

In [34]:
#load dataset

df=pd.read_csv("train.csv",usecols=["Age","Fare","Survived"])

In [35]:
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [7]:
df.shape

(891, 3)

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.impute import MissingIndicator
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression

In [36]:
x=df.drop(columns=["Survived"])
y=df["Survived"]

In [37]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [15]:
x_train.head()

      Age     Fare
30   40.0  27.7208
10    4.0  16.7000
873  47.0   9.0000
182   9.0  31.3875
876  20.0   9.8458

In [19]:
#Without missing indicator

In [16]:
si=SimpleImputer()

x_train_si=si.fit_transform(x_train)
x_test_si=si.transform(x_test)

In [18]:
lr=LogisticRegression()
lr.fit(x_train_si,y_train)

y_pred=lr.predict(x_test_si)

print(accuracy_score(y_test,y_pred))

0.6145251396648045

In [21]:
#with missing indicator

In [22]:
mi=MissingIndicator()

x_train_missing=mi.fit_transform(x_train)
x_test_missing=mi.transform(x_test)

In [24]:
x_train["Age_NAN"]=x_train_missing
x_test["Age_NAN"]=x_test_missing

In [26]:
x_train.sample(5)

      Age      Fare  Age_NAN
334   NaN  133.6500     True
554  22.0    7.7750    False
388   NaN    7.7292     True
701  35.0   26.2875    False
405  34.0   21.0000    False

In [30]:
si2=SimpleImputer()

x_train_trf2=si2.fit_transform(x_train)
x_test_trf2=si2.transform(x_test)

In [31]:
lr2=LogisticRegression()

lr2.fit(x_train_trf2,y_train)

y_pred2=lr2.predict(x_test_trf2)

print(accuracy_score(y_test,y_pred2))

0.6312849162011173

In [32]:
#more Simple code for  missing indicator

In [39]:
x_train.head()

      Age     Fare
30   40.0  27.7208
10    4.0  16.7000
873  47.0   9.0000
182   9.0  31.3875
876  20.0   9.8458

In [41]:
si3=SimpleImputer(add_indicator=True)

x_train_trf3=si3.fit_transform(x_train)
x_test_trf3=si3.transform(x_test)

In [42]:
lr3=LogisticRegression()

lr3.fit(x_train_trf3,y_train)

y_pred3=lr3.predict(x_test_trf3)

print(accuracy_score(y_test,y_pred3))

0.6312849162011173